#include QMK_KEYBOARD_H

enum layers {
	LAYER_STI,
	LAYER_FLU,
	LAYER_QZ,
	LAYER_NUMPAD,
	LAYER_FN,
	LAYER_NAV
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[LAYER_STI] = LAYOUT_split_3x5_3(
		KC_LALT, KC_S, KC_T, KC_I, KC_TAB, 
		KC_TAB, KC_I, KC_T, KC_S, KC_RALT, 

		KC_LCTL, KC_A, KC_O, KC_E, KC_ESC,
		KC_ESC, KC_E, KC_O, KC_A, KC_RCTL,

		KC_LSFT, KC_N, KC_H, KC_R, KC_BACKSPACE, 
		KC_BACKSPACE, KC_R, KC_H, KC_N, KC_RSFT, 

		MO(LAYER_QZ), MO(LAYER_FLU), MO(LAYER_NUMPAD), 
		MO(LAYER_NUMPAD), MO(LAYER_FLU), MO(LAYER_QZ)
	),

	[LAYER_FLU] = LAYOUT_split_3x5_3(
		KC_LALT, KC_D, KC_V, KC_Y, KC_INS, 
		KC_INS, KC_Y, KC_V, KC_D, KC_RALT, 

		KC_LCTL, KC_F, KC_L, KC_U, KC_NO, 
		KC_NO, KC_U, KC_L, KC_F, KC_RCTL, 

		KC_LSFT, KC_M, KC_C, KC_G, KC_DELETE, 
		KC_DELETE, KC_G, KC_C, KC_M, KC_LSFT, 

		MO(LAYER_NAV), KC_NO, MO(LAYER_FN), 
		MO(LAYER_FN), KC_NO, MO(LAYER_NAV)
	),

	[LAYER_QZ] = LAYOUT_split_3x5_3(
		KC_LALT, KC_P, KC_B, KC_K, KC_SCRL,
		KC_SCRL, KC_K, KC_B, KC_P, KC_RALT, 
		
		KC_LCTL, KC_W, KC_J, KC_X, KC_NO,
		KC_NO, KC_X, KC_J, KC_W, KC_RCTL, 

		KC_LSFT, KC_Q, KC_Z, KC_GRV, KC_NO, 
		KC_NO, KC_GRV, KC_Z, KC_Q, KC_RSFT, 

		KC_NO, MO(LAYER_NAV), KC_NO, 
		KC_NO, MO(LAYER_NAV), KC_NO
	),

	[LAYER_NUMPAD] = LAYOUT_split_3x5_3(
		KC_LALT, KC_KP_7, KC_KP_8, KC_KP_9, KC_NUM, 
		KC_NUM, KC_KP_9, KC_KP_8, KC_KP_7, KC_RALT, 

		KC_RSFT, KC_KP_4, KC_KP_5, KC_KP_6, KC_NO, 
		KC_NO, KC_KP_6, KC_KP_5, KC_KP_4, KC_RSFT, 

		KC_LSFT, KC_KP_1, KC_KP_2, KC_KP_3, KC_BACKSPACE, 
		KC_BACKSPACE, KC_KP_3, KC_KP_2, KC_KP_1, KC_RSFT, 

		KC_NO, MO(LAYER_FN), KC_NO, 
		KC_NO, MO(LAYER_FN), KC_NO
	),

	[LAYER_FN] = LAYOUT_split_3x5_3(
		KC_LALT, KC_F1, KC_F2, KC_F3, KC_F4, 
		KC_F4, KC_F3, KC_F2, KC_F1, KC_RALT, 

		KC_LCTL, KC_F5, KC_F6, KC_F7, KC_F8, 
		KC_F8, KC_F7, KC_F6, KC_F5, KC_RCTL, 

		KC_LSFT, KC_F9, KC_F10, KC_F11, KC_F12, 
		KC_F12, KC_F11, KC_F10, KC_F9, KC_RSFT, 

		KC_NO, KC_NO, KC_NO, 
		KC_NO, KC_NO, KC_NO
	),

	
	[LAYER_NAV] = LAYOUT_split_3x5_3(
		KC_LALT, KC_HOME, KC_UP, KC_END, KC_MEDIA_NEXT_TRACK, 
		KC_MEDIA_NEXT_TRACK, KC_F3, KC_UP, KC_F1, KC_RALT, 

		KC_LCTL, KC_LEFT, KC_DOWN, KC_RIGHT, KC_MEDIA_PREV_TRACK, 
		KC_MEDIA_PREV_TRACK, KC_LEFT, KC_DOWN, KC_RIGHT, KC_RCTL, 

		KC_LSFT, KC_AUDIO_MUTE, KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP, KC_MEDIA_PLAY_PAUSE, 
		KC_F12, KC_F11, KC_F10, KC_F9, KC_RSFT, 

		KC_NO, KC_NO, KC_NO, 
		KC_NO, KC_NO, KC_NO
	)
};

/* Combos */

/* Layer 0 (STI) combos */
const uint16_t PROGMEM COMBO_S_T[] = {KC_S, KC_T, COMBO_END};
const uint16_t PROGMEM COMBO_T_I[] = {KC_T, KC_I, COMBO_END};
const uint16_t PROGMEM COMBO_S_T_I[] = {KC_S, KC_T, KC_I, COMBO_END};

const uint16_t PROGMEM COMBO_A_O[] = {KC_A, KC_O, COMBO_END};
const uint16_t PROGMEM COMBO_O_E[] = {KC_O, KC_E, COMBO_END};
const uint16_t PROGMEM COMBO_A_O_E[] = {KC_A, KC_O, KC_E, COMBO_END};

const uint16_t PROGMEM COMBO_N_H[] = {KC_N, KC_H, COMBO_END};
const uint16_t PROGMEM COMBO_H_R[] = {KC_H, KC_R, COMBO_END};
const uint16_t PROGMEM COMBO_N_H_R[] = {KC_N, KC_H, KC_R, COMBO_END};

const uint16_t PROGMEM COMBO_BKSP_ESC[] = {KC_BACKSPACE, KC_ESC, COMBO_END};

/* Layer 1 (FLU) combos */
const uint16_t PROGMEM COMBO_D_V[] = {KC_D, KC_V, COMBO_END};
const uint16_t PROGMEM COMBO_V_Y[] = {KC_V, KC_Y, COMBO_END};
const uint16_t PROGMEM COMBO_D_V_Y[] = {KC_D, KC_V, KC_Y, COMBO_END};

const uint16_t PROGMEM COMBO_F_L[] = {KC_F, KC_L, COMBO_END};
const uint16_t PROGMEM COMBO_L_U[] = {KC_L, KC_U, COMBO_END};
const uint16_t PROGMEM COMBO_F_L_U[] = {KC_F, KC_L, KC_U, COMBO_END};

const uint16_t PROGMEM COMBO_M_C[] = {KC_M, KC_C, COMBO_END};
const uint16_t PROGMEM COMBO_C_G[] = {KC_C, KC_G, COMBO_END};
const uint16_t PROGMEM COMBO_M_C_G[] = {KC_M, KC_C, KC_G, COMBO_END};

/* Layer 2 (QZ) combos */
const uint16_t PROGMEM COMBO_P_B[] = {KC_P, KC_B, COMBO_END};
const uint16_t PROGMEM COMBO_B_K[] = {KC_B, KC_K, COMBO_END};
const uint16_t PROGMEM COMBO_P_B_K[] = {KC_P, KC_B, KC_K, COMBO_END};

const uint16_t PROGMEM COMBO_W_J[] = {KC_W, KC_J, COMBO_END};
const uint16_t PROGMEM COMBO_J_X[] = {KC_J, KC_X, COMBO_END};
const uint16_t PROGMEM COMBO_W_J_X[] = {KC_W, KC_J, KC_X, COMBO_END};

const uint16_t PROGMEM COMBO_Q_Z[] = {KC_Q, KC_Z, COMBO_END};
const uint16_t PROGMEM COMBO_Z_GRV[] = {KC_Z, KC_GRV, COMBO_END};
const uint16_t PROGMEM COMBO_Q_Z_GRV[] = {KC_Q, KC_Z, KC_GRV, COMBO_END};

/* Layer 3 (NUMPAD) combos */
const uint16_t PROGMEM COMBO_7_8[] = {KC_KP_7, KC_KP_8, COMBO_END};
const uint16_t PROGMEM COMBO_8_9[] = {KC_KP_8, KC_KP_9, COMBO_END};
const uint16_t PROGMEM COMBO_7_8_9[] = {KC_KP_7, KC_KP_8, KC_KP_9, COMBO_END};
const uint16_t PROGMEM COMBO_4_5[] = {KC_KP_4, KC_KP_5, COMBO_END};
const uint16_t PROGMEM COMBO_5_6[] = {KC_KP_5, KC_KP_6, COMBO_END};
const uint16_t PROGMEM COMBO_4_5_6[] = {KC_KP_4, KC_KP_5, KC_KP_6, COMBO_END};
const uint16_t PROGMEM COMBO_1_2[] = {KC_KP_1, KC_KP_2, COMBO_END};
const uint16_t PROGMEM COMBO_2_3[] = {KC_KP_2, KC_KP_3, COMBO_END};
const uint16_t PROGMEM COMBO_1_2_3[] = {KC_KP_1, KC_KP_2, KC_KP_3, COMBO_END};



combo_t key_combos[] = {
  /* Layer 0 */
  COMBO(COMBO_S_T, KC_BACKSLASH),
  COMBO(COMBO_T_I, KC_DOT),
  COMBO(COMBO_S_T_I, KC_NO),
  COMBO(COMBO_A_O, KC_QUOTE),
  COMBO(COMBO_O_E, KC_COMM),
  COMBO(COMBO_A_O_E, KC_NO),
  COMBO(COMBO_N_H, KC_SEMICOLON),
  COMBO(COMBO_H_R, KC_SPACE),
  COMBO(COMBO_N_H_R, KC_ENTER),
  COMBO(COMBO_BKSP_ESC, OSM(MOD_LGUI)),
  

  /* Layer 1 */
  COMBO(COMBO_D_V, KC_LEFT_BRACKET),
  COMBO(COMBO_V_Y, KC_RIGHT_BRACKET),
  COMBO(COMBO_D_V_Y, KC_NO),
  COMBO(COMBO_F_L, RSFT(KC_9)),
  COMBO(COMBO_L_U, RSFT(KC_0)),
  COMBO(COMBO_F_L_U, KC_NO),
  COMBO(COMBO_M_C, KC_NO),
  COMBO(COMBO_C_G, KC_SPACE),
  COMBO(COMBO_M_C_G, KC_ENTER),

  /* Layer 2 */
  COMBO(COMBO_P_B, RSFT(KC_SLASH)),
  COMBO(COMBO_B_K, RSFT(KC_1)),
  COMBO(COMBO_P_B_K, RSFT(KC_4)),
  COMBO(COMBO_W_J, RSFT(KC_6)),
  COMBO(COMBO_J_X, RSFT(KC_2)),
  COMBO(COMBO_W_J_X, KC_NO),
  COMBO(COMBO_Q_Z, RSFT(KC_3)),
  COMBO(COMBO_Z_GRV, KC_SPACE),
  COMBO(COMBO_Q_Z_GRV, KC_ENTER),

  /* Layer 3 */
  COMBO(COMBO_7_8, KC_KP_SLASH),
  COMBO(COMBO_8_9, KC_KP_ASTERISK),
  COMBO(COMBO_7_8_9, RSFT(KC_5)),
  COMBO(COMBO_4_5, KC_KP_MINUS),
  COMBO(COMBO_5_6, KC_KP_PLUS),
  COMBO(COMBO_4_5_6, KC_EQUAL),
  COMBO(COMBO_1_2, KC_KP_0),
  COMBO(COMBO_2_3, KC_KP_DOT),
  COMBO(COMBO_1_2_3, KC_KP_ENTER),
};
